extends: default.yaml

project:
  video_id: "L21_V001"
  frames_dir: "/home/maitanha/AIC2026/AIC-Test/keyframe_test/L21_V001"
  output_dir: "/home/maitanha/AIC2026/AIC-Test/data_processing/OCR/ocr_vlm_pipeline/outputs/L21_V001"
  resume: true

runtime:
  device: "cuda:0"
  num_workers_io: 8
  save_every_n_frames: 100
  log_every_n_frames: 25

vlm:
  device: "cuda:0"
  device_map: "cuda:0"
  batch_size: 1
  cache_path: "/home/maitanha/AIC2026/AIC-Test/data_processing/OCR/ocr_vlm_pipeline/outputs/L21_V001/vlm_cache.sqlite"

es:
  index_name: "video_frames_l21_test"
