# -*- coding: utf-8 -*-
"""Co-DETR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQuxq95D9SmOtTGDaxWa4BbhHyURlv6X
"""

# Commented out IPython magic to ensure Python compatibility.
# 1. Tải và cài đặt tự động một bản Miniconda độc lập
!wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!bash Miniconda3-latest-Linux-x86_64.sh -b -p /content/miniconda

# 2. Tự động chấp nhận Điều khoản dịch vụ (ToS) của Anaconda
!/content/miniconda/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
!/content/miniconda/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
!/content/miniconda/bin/conda config --add channels conda-forge

# 3. SỬA LỖI: Bắt buộc gọi thêm 'pip' ở cuối để Conda cài đặt sẵn công cụ pip cho môi trường ảo
!/content/miniconda/bin/conda create -n codetr python=3.9 pip -y

# 4. Thiết lập các biến môi trường trỏ vào env ảo
# %env ENV_PIP=/content/miniconda/envs/codetr/bin/pip
# %env ENV_PYTHON=/content/miniconda/envs/codetr/bin/python

# 5. Cài đặt PyTorch 1.12.1 cấu hình CUDA 11.3 (Lần này pip đã tồn tại và sẽ chạy thành công)
!$ENV_PIP install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113

# Commented out IPython magic to ensure Python compatibility.
# 1. Cài đặt gói quản lý openmim vào môi trường ảo
!$ENV_PIP install openmim

# 2. Xác định đường dẫn thực thi của lệnh 'mim' vừa cài đặt
# %env ENV_MIM=/content/miniconda/envs/codetr/bin/mim

# 3. Tiến hành cài đặt chính xác bản build cũ mmcv-full và mmdet
!$ENV_MIM install mmcv-full==1.5.0
!$ENV_MIM install mmdet==2.25.3

# 4. Cài thêm các tiện ích bổ sung phục vụ tải file và vẽ đồ thị kết quả
!$ENV_PIP install huggingface_hub matplotlib

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Sense-X/Co-DETR.git
# %cd Co-DETR

import huggingface_hub
huggingface_hub.hf_hub_download(
    repo_id='zongzhuofan/co-detr-vit-large-lvis',
    filename='pytorch_model.pth',
    local_dir='./checkpoints'
)

# 3. Đổi tên file vừa tải sang pytorch_model_lvis.pth để dễ phân biệt
!mv checkpoints/pytorch_model.pth checkpoints/pytorch_model_lvis.pth

print("--> Đã tải xong trọng số LVIS và lưu tại checkpoints/pytorch_model_lvis.pth")

# 1. Ép pip cài đặt bản wheel mmcv-full 1.6.0 đã được dựng sẵn cho Torch 1.12
!$ENV_PIP install mmcv-full==1.6.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.12.0/index.html

# 2. Cài đặt mmdet vào thẳng môi trường ảo để đảm bảo đồng bộ cấu trúc
!$ENV_PIP install mmdet==2.25.3

!$ENV_PIP install einops fairscale fvcore scipy timm "numpy < 2"

# Ghi đè mã nguồn bổ sung điểm score và vị trí box cho từng thực thể
script_content = """
import os
import sys
import collections

# Khóa cứng backend đồ họa ngầm để tránh lỗi giao diện hiển thị của Colab
import matplotlib
matplotlib.use('Agg')

import cv2

sys.path.append('.')
from mmdet.apis import init_detector, inference_detector
# Lấy trực tiếp Class Dataset của LVIS v1
from mmdet.datasets.lvis import LVISV1Dataset

def run_counter():
    config_path = 'projects/configs/co_dino_vit/co_dino_5scale_lsj_vit_large_lvis.py'
    checkpoint_path = 'checkpoints/pytorch_model_lvis.pth'
    img_path = '/content/013.jpg'
    score_thr = 0.4

    print("--> Đang nạp mô hình Co-DINO ViT-Large (LVIS) vào GPU... Vui lòng đợi...")
    model = init_detector(config_path, checkpoint_path, device='cuda:0')

    # Ép mô hình nạp đúng 1203 tên lớp được định nghĩa trong LVISV1Dataset
    print("--> Đang đồng bộ tập từ vựng LVIS (1.203 lớp)...")
    model.CLASSES = LVISV1Dataset.CLASSES

    print("--> Khởi tạo thành công! Đang tiến hành quét và bóc tách thực thể...")

    # Chạy dự đoán mạng nơ-ron
    result = inference_detector(model, img_path)

    object_counts = collections.defaultdict(int)
    detailed_objects = [] # Danh sách lưu thông tin chi tiết từng thực thể

    # Duyệt qua kết quả đầu ra của 1203 lớp LVIS để lọc, đếm và lấy tọa độ
    for class_idx, bboxes in enumerate(result):
        class_name = model.CLASSES[class_idx]
        for bbox in bboxes:
            score = bbox[4]
            if score >= score_thr:
                # 1. Tăng biến đếm số lượng tổng quan
                object_counts[class_name] += 1

                # 2. Trích xuất tọa độ [x_min, y_min, x_max, y_max] và làm tròn 2 chữ số thập phân
                box_coords = [round(float(coord), 2) for coord in bbox[:4]]

                # 3. Lưu thông tin vào danh sách chi tiết
                detailed_objects.append({
                    "name": class_name,
                    "score": round(float(score), 4),
                    "box": box_coords
                })

    # BẢNG THỐNG KÊ 1: Số lượng tổng quan theo từng phân lớp
    print("\\n" + "="*65)
    print(f"   [1] BẢNG THỐNG KÊ SỐ LƯỢNG TỔNG QUAN (Score >= {score_thr})")
    print("="*65)
    if len(object_counts) == 0:
        print("❌ Không tìm thấy thực thể nào đạt đủ độ tin cậy.")
    else:
        sorted_counts = sorted(object_counts.items(), key=lambda x: x[1], reverse=True)
        for obj_name, count in sorted_counts:
            print(f"🔹 {obj_name.upper():<20} : {count} thực thể")
    print("="*65 + "\\n")

    # BẢNG THỐNG KÊ 2: Vị trí tọa độ và điểm score chi tiết của từng thực thể
    print("="*65)
    print(f"   [2] DANH SÁCH TỌA ĐỘ BOX VÀ SCORE CHI TIẾT TỪNG THỰC THỂ")
    print("="*65)
    if len(detailed_objects) == 0:
        print("❌ Không có dữ liệu chi tiết thực thể.")
    else:
        # Sắp xếp danh sách chi tiết theo điểm số score giảm dần
        sorted_details = sorted(detailed_objects, key=lambda x: x['score'], reverse=True)
        for idx, obj in enumerate(sorted_details, 1):
            print(f"🔸 {idx:02d}. {obj['name'].upper():<15} : score={obj['score']:.3f}  box={obj['box']}")
    print("="*65 + "\\n")

    # Vẽ khung Bounding Box kèm nhãn LVIS và lưu ảnh kết quả
    model.show_result(img_path, result, out_file='output_counted_lvis.jpg', score_thr=score_thr)
    print("--> Đã xử lý xong và xuất file output_counted_lvis.jpg thành công!")

if __name__ == '__main__':
    run_counter()
"""

with open("counter_script.py", "w") as f:
    f.write(script_content)

print("--> Đã cập nhật cấu trúc mã nguồn! Tiến hành kích hoạt mô hình...")

# Thực thi tệp tin bằng môi trường ảo Python 3.9 độc lập
!MPLBACKEND=Agg /content/miniconda/envs/codetr/bin/python counter_script.py

import cv2
import matplotlib.pyplot as plt

# Đọc và chuyển đổi hệ màu ảnh từ BGR sang RGB để hiển thị đúng bằng matplotlib
final_img = cv2.imread('output_counted_lvis.jpg')
final_img = cv2.cvtColor(final_img, cv2.COLOR_BGR2RGB)

# Hiển thị ảnh kích thước lớn
plt.figure(figsize=(14, 10))
plt.imshow(final_img)
plt.axis('off')
plt.show()