# -*- coding: utf-8 -*-
"""GroundingDINO_RAM++.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZEXpI7EuooyXMmSNUYOQfeElf22NUvwK

# Bo sung Grounding DINO vao Pipeline Multi-Modal Retrieval (MMRS-LMF)

Notebook nay **mo rong** notebook RAM++ goc (`RAM__.ipynb`) de minh hoa day du luong xu ly
**Tag Detection (RAM) -> Object Detection (Grounding DINO)** dung theo kien truc mo ta trong
Hinh 2 (Fig. 2 -- *Multi Modal Retrieval architecture*) va muc **4.4 Tags and Objects Detection**
cua paper *"Transforming Video Search: Leveraging Multimodal Techniques and LLMs for Optimal Retrieval"*.

Theo paper:

> *"The RAM model analyzes semantic image information... to create tags... The method uses the
> Grounding DINO model... to forecast bounding boxes for image tags."*

Noi cach khac: **tags tu RAM++ duoc dung lam text-prompt dau vao cho Grounding DINO** de dinh vi
(localize) chinh cac doi tuong do trong khung hinh (keyframe), tao ra `bounding boxes of tags` --
mot nhanh du lieu doc lap voi nhanh Tag Detection, sau do ca hai duoc nap vao Elasticsearch.

Pipeline day du trong notebook nay:

```
Keyframe -----> [1] RAM++  -----> list tags (text)
   |                                   |
   |                                   v
   +--------------------------> [2] Grounding DINO (zero-shot, prompt = tags)
                                       |
                                       v
                              [3] Bounding boxes + scores theo tung tag
                                       |
                                       v
                              [4] Ve minh hoa len anh
                                       |
                                       v
                              [5] Dong goi JSON metadata (san sang index vao Elasticsearch)
```

## 0. Cai dat moi truong

Cai dat day du cho ca hai nhanh model:
- **RAM++** (`recognize-anything`) -- nhanh Tag Detection (giong notebook goc).
- **Grounding DINO** -- nhanh Object Detection. O day dung ban tich hop san trong
  `transformers` (`AutoModelForZeroShotObjectDetection`) thay vi repo goc `IDEA-Research/GroundingDINO`,
  vi ban HuggingFace **khong can compile CUDA ops** (`MultiScaleDeformableAttention`), chay on dinh
  tren Colab T4 va cho ket qua tuong duong.

### Vi sao phai PIN `transformers==4.46.3` (rat quan trong, doc truoc khi chay)

Source code cua `recognize-anything` (file `ram/models/bert.py`, `ram/models/utils.py`) duoc viet
theo phong cach BLIP cu, import truc tiep cac ham noi bo nhu `apply_chunking_to_forward`,
`find_pruneable_heads_and_indices` tu `transformers.modeling_utils`, va dung thuoc tinh
`tokenizer.additional_special_tokens_ids`. Cac ham/thuoc tinh nay **da bi go bo** trong cac ban
`transformers` qua moi (tu ~4.47 tro len, va bi go het hoan toan o ban 5.x), gay loi dung
`ImportError: cannot import name 'apply_chunking_to_forward' from 'transformers.modeling_utils'`
neu ban vo tinh `pip install -U transformers`.

Trong khi do, Grounding DINO chi duoc HuggingFace tich hop tu ban `transformers==4.40.0`.
=> **`4.46.3` la ban cuoi cung thoa man dong thoi ca hai dieu kien**: vua co san model
Grounding DINO, vua con giu day du cac API noi bo cu ma RAM++ can. Vi vay TOAN BO notebook nay
pin cung mot phien ban `transformers==4.46.3`, **khong duoc nang cap** (`pip install -U ...`)
o bat ky cell nao phia sau, neu khong loi tren se lap lai.
"""

# ====== 0.1. Cai dat RAM++ (nhanh Tag Detection) ======
# QUAN TRONG: pin dung "transformers==4.46.3" -- xem giai thich o markdown phia tren.
!pip install -q git+https://github.com/xinyu1205/recognize-anything.git
!pip install -q timm "transformers==4.46.3" accelerate pillow torch torchvision fairscale

# Tai trong so RAM++ (Swin-Large, 14M)
!mkdir -p pretrained
!wget -q -O pretrained/ram_plus_swin_large_14m.pth https://huggingface.co/xinyu1205/recognize-anything-plus-model/resolve/main/ram_plus_swin_large_14m.pth

# Anh mau de test nhanh (co the thay bang keyframe thuc te trich tu TransNetV2)
!mkdir -p images
!wget -q -O images/demo.jpg https://raw.githubusercontent.com/xinyu1205/recognize-anything/main/images/demo/demo1.jpg

print("Da cai dat xong nhanh RAM++.")

# ====== 0.2. Cai dat Grounding DINO (nhanh Object Detection) ======
# KHONG goi "pip install -U transformers" o day -- se lam nang cap transformers va
# pha vo nhanh RAM++ o tren (xem giai thich muc 0). Grounding DINO da co san trong
# ban "transformers==4.46.3" da cai o cell truoc, nen chi can cai them "supervision"
# (tuy chon, dung de ve bounding box) va kiem tra lai cho chac chan.
!pip install -q supervision

import transformers
assert transformers.__version__ == "4.46.3", (
    f"transformers dang la {transformers.__version__}, can dung 4.46.3 de tranh xung dot "
    f"voi RAM++. Hay chay lai cell 0.1 va KHONG chay lenh pip install -U transformers o dau khac."
)
print(f"transformers=={transformers.__version__} -- OK, sẵn sàng cho cả RAM++ và Grounding DINO.")

"""## 1. Nhanh Tag Detection -- RAM++

Dong goi lai logic suy luan RAM++ thanh mot ham `get_ram_tags()` de co the tai su dung
cho moi keyframe trong pipeline, thay vi viet code roi rac nhu notebook goc.

"""

import torch
from PIL import Image
from ram.models import ram_plus
from ram import inference_ram as inference
from ram import get_transform

# ---- Thiet lap thiet bi & nap mo hinh RAM++ (chi load mot lan) ----
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Dang chay tren thiet bi: {device}")

RAM_IMAGE_SIZE = 384
RAM_CHECKPOINT = "pretrained/ram_plus_swin_large_14m.pth"

print("Dang nap mo hinh RAM++ (Swin-Large)...")
ram_model = ram_plus(pretrained=RAM_CHECKPOINT, image_size=RAM_IMAGE_SIZE, vit='swin_l')
ram_model.eval()
ram_model = ram_model.to(device)
ram_transform = get_transform(image_size=RAM_IMAGE_SIZE)
print("RAM++ da san sang.")


def get_ram_tags(image: Image.Image):
    """Chay RAM++ tren mot anh PIL, tra ve danh sach tag tieng Anh da lam sach.

    Tuong ung module 'Tag Detection (RAM)' trong Fig. 2 cua paper -> output la
    'List tags of objects in frame'.
    """
    image_tensor = ram_transform(image.convert("RGB")).unsqueeze(0).to(device)
    with torch.no_grad():
        res = inference(image_tensor, ram_model)

    raw_tags = res[0]  # vi du: "dog | grass | playing"
    tag_list = [t.strip() for t in raw_tags.split("|") if t.strip()]
    return tag_list


# ---- Test nhanh ----
test_image_path = "/content/089.jpg"
test_image = Image.open(test_image_path)
ram_tags = get_ram_tags(test_image)
print(f"Tags tu RAM++ ({len(ram_tags)}): {ram_tags}")

"""## 2. Nhanh Object Detection -- Grounding DINO

Day la phan **bo sung chinh** theo yeu cau: dung chinh cac tag vua lay duoc tu RAM++ lam
**text prompt** cho Grounding DINO de thuc hien *zero-shot object detection*, tu do suy ra
bounding box cho tung tag -- dung nhu mo ta o muc 4.4 cua paper:

> *"...to forecast bounding boxes for image tags... a feature improvement component,
> linguistic question selection, and a multimodal decoder that improves linguistic
> integration over standard detectors."*

"""

from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection

# Co 2 lua chon checkpoint:
#   - "IDEA-Research/grounding-dino-tiny"  -> nhe, toc do nhanh, phu hop demo / Colab T4
#   - "IDEA-Research/grounding-dino-base"  -> chinh xac cao hon, dung khi trien khai thuc
GROUNDING_DINO_MODEL_ID = "IDEA-Research/grounding-dino-base"

print(f"Dang nap mo hinh Grounding DINO: {GROUNDING_DINO_MODEL_ID} ...")
dino_processor = AutoProcessor.from_pretrained(GROUNDING_DINO_MODEL_ID)
dino_model = AutoModelForZeroShotObjectDetection.from_pretrained(GROUNDING_DINO_MODEL_ID).to(device)
dino_model.eval()
print("Grounding DINO da san sang.")

def build_dino_prompt(tag_list):
    """Chuyen danh sach tag tu RAM++ thanh text-prompt dung cu phap Grounding DINO.

    Quy uoc chuan cua Grounding DINO: 1 chuoi duy nhat, chu thuong, cac phrase
    cach nhau boi ". " va KET THUC bang dau cham. Vi du:
    "person. kitchen. apron. counter top."
    (Luu y: ban transformers 4.46.3 dang pin trong notebook nay CHUA ho tro tham so
    tien loi `text_labels` (list-of-list) cua cac ban moi hon -- phai dung chuoi text
    don + tu giai ma label tu input_ids.)
    """
    phrases = [tag.lower().strip() for tag in tag_list if tag.strip()]
    return ". ".join(phrases) + "."


def detect_objects_with_dino(image: Image.Image, tag_list,
                              box_threshold: float = 0.35,
                              text_threshold: float = 0.25):
    """Chay Grounding DINO zero-shot detection voi prompt = cac tag tu RAM++.

    Tra ve list cac dict: {"label": str, "score": float, "box": [x0, y0, x1, y1]}
    (toa do theo pixel, da quy doi ve kich thuoc anh goc).
    """
    # CHỈNH SỬA TẠI ĐÂY: Ép ảnh về định dạng RGB 3 kênh tiêu chuẩn để xóa bỏ kênh RGBA/Alpha lỗi
    image = image.convert("RGB")

    text_prompt = build_dino_prompt(tag_list)

    inputs = dino_processor(images=image, text=text_prompt, return_tensors="pt").to(device)
    with torch.no_grad():
        outputs = dino_model(**inputs)

    results = dino_processor.post_process_grounded_object_detection(
        outputs,
        inputs.input_ids,
        box_threshold=box_threshold,
        text_threshold=text_threshold,
        target_sizes=[image.size[::-1]],  # (height, width)
    )
    result = results[0]  # batch size = 1

    detections = []
    for box, score, label in zip(result["boxes"], result["scores"], result["labels"]):
        detections.append({
            "label": label.strip(),
            "score": round(score.item(), 4),
            "box": [round(coord, 2) for coord in box.tolist()],  # [x0, y0, x1, y1]
        })
    return detections


# ---- Test nhanh: dung chinh cac tag RAM++ lay o buoc 1 ----
detections = detect_objects_with_dino(test_image, ram_tags)
print(f"Prompt gui cho Grounding DINO: {build_dino_prompt(ram_tags)}")
print(f"Grounding DINO tim duoc {len(detections)} bounding box:")
for d in detections:
    print(f"  - {d['label']:<20} score={d['score']:.3f}  box={d['box']}")

"""## 3. Truc quan hoa bounding box

Ve ket qua "Bounding boxes of tags" len khung hinh de kiem tra truc quan, tuong tu
hop mau xanh trong Fig. 2 cua paper.

"""

from PIL import ImageDraw, ImageFont
import itertools

PALETTE = ["#FF3B30", "#34C759", "#007AFF", "#FF9500", "#AF52DE", "#00C7BE", "#FFD60A"]

def draw_detections(image: Image.Image, detections, save_path=None):
    """Ve bounding box + label + confidence score len anh, tra ve anh da annotate."""
    annotated = image.convert("RGB").copy()
    draw = ImageDraw.Draw(annotated)
    color_cycle = itertools.cycle(PALETTE)

    try:
        font = ImageFont.truetype("DejaVuSans-Bold.ttf", 16)
    except Exception:
        font = ImageFont.load_default()

    for det, color in zip(detections, color_cycle):
        x0, y0, x1, y1 = det["box"]
        text = f"{det['label']} {det['score']:.2f}"

        draw.rectangle([x0, y0, x1, y1], outline=color, width=3)
        text_bbox = draw.textbbox((x0, y0), text, font=font)
        draw.rectangle(
            [text_bbox[0], text_bbox[1] - 4, text_bbox[2] + 4, text_bbox[3] + 2],
            fill=color,
        )
        draw.text((x0 + 2, y0 - 18), text, fill="white", font=font)

    if save_path:
        annotated.save(save_path)
    return annotated


annotated_image = draw_detections(test_image, detections, save_path="images/demo_with_boxes.jpg")
display(annotated_image)

"""## 4. Dong goi metadata -- san sang index vao Elasticsearch

Theo Fig. 2 cua paper, output cua hai nhanh **Tag Detection (RAM)** va **Object Detection
(Grounding DINO)** deu do vao **Database (Elasticsearch)** duoi dang cac field rieng cua moi
keyframe. Ham duoi day mo phong dung schema do.

"""

import json
from datetime import datetime

def build_frame_metadata(frame_id: str, video_id: str, ram_tags, dino_detections):
    """Dong goi ket qua Tag Detection + Object Detection thanh 1 document
    theo schema tuong tu custom index cua Elasticsearch trong paper (muc 5.1).
    """
    return {
        "frame_id": frame_id,
        "video_id": video_id,
        "timestamp_indexed": datetime.utcnow().isoformat(),
        "tags": ram_tags,                       # tu nhanh RAM (Tag Detection)
        "objects": [                              # tu nhanh Grounding DINO (Object Detection)
            {
                "tag": det["label"],
                "confidence": det["score"],
                "bbox_xyxy": det["box"],
            }
            for det in dino_detections
        ],
    }


frame_metadata = build_frame_metadata(
    frame_id="demo_frame_0001",
    video_id="demo_video",
    ram_tags=ram_tags,
    dino_detections=detections,
)

print(json.dumps(frame_metadata, indent=2, ensure_ascii=False))

"""## 5. Pipeline tong hop end-to-end

Gop toan bo cac buoc tren thanh mot ham duy nhat `process_keyframe()`, co the goi lap lai
cho tung keyframe duoc TransNetV2 trich xuat (theo muc 3.1 cua paper), tao thanh quy trinh
batch xu ly cho toan bo tap du lieu ~300h / ~32.5M khung hinh.

"""

def process_keyframe(image_path: str, frame_id: str, video_id: str,
                      box_threshold: float = 0.35, text_threshold: float = 0.25,
                      visualize: bool = True, save_dir: str = "images/annotated"):
    """Pipeline day du cho 1 keyframe: RAM++ -> Grounding DINO -> metadata JSON.

    Mapping voi Fig. 2 cua paper:
      Extract Keyframes -> [Tag Detection (RAM)] -> [Object Detection (Grounding DINO)]
                         -> Database (Elasticsearch)
    """
    # CHỈNH SỬA TẠI ĐÂY: Đảm bảo ép kiểu RGB ngay từ bước mở file từ ổ đĩa
    image = Image.open(image_path).convert("RGB")

    # [1] Tag Detection (RAM)
    tags = get_ram_tags(image)

    # [2] Object Detection (Grounding DINO) -- dung chinh tags vua sinh ra lam prompt
    dets = detect_objects_with_dino(
        image, tags, box_threshold=box_threshold, text_threshold=text_threshold
    )

    # [3] Truc quan hoa (tuy chon, huu ich khi debug / demo)
    if visualize:
        import os
        os.makedirs(save_dir, exist_ok=True)
        save_path = os.path.join(save_dir, f"{frame_id}.jpg")
        draw_detections(image, dets, save_path=save_path)

    # [4] Dong goi metadata san sang dua vao Elasticsearch
    metadata = build_frame_metadata(frame_id, video_id, tags, dets)
    return metadata


# ---- Demo chay pipeline cho 1 keyframe ----
result = process_keyframe(
    image_path="images/demo.jpg",
    frame_id="demo_frame_0001",
    video_id="demo_video",
)
print(json.dumps(result, indent=2, ensure_ascii=False))

# ---- Demo chay pipeline cho NHIEU keyframe (batch), giong thuc te xu ly 1 video ----
import glob

keyframe_paths = sorted(glob.glob("images/*.jpg"))
all_metadata = []

for idx, path in enumerate(keyframe_paths):
    fid = f"frame_{idx:04d}"
    meta = process_keyframe(path, frame_id=fid, video_id="demo_video", visualize=False)
    all_metadata.append(meta)
    print(f"[{idx+1}/{len(keyframe_paths)}] {fid}: {len(meta['tags'])} tags, "
          f"{len(meta['objects'])} bounding boxes")

# Luu toan bo metadata ra file .jsonl, san sang bulk-index vao Elasticsearch
with open("frame_metadata.jsonl", "w", encoding="utf-8") as f:
    for meta in all_metadata:
        f.write(json.dumps(meta, ensure_ascii=False) + "\n")

print(f"\nDa luu metadata cua {len(all_metadata)} keyframe vao frame_metadata.jsonl")

"""## 6. Ghi chu trien khai thuc te

- **Phien ban `transformers`**: notebook nay PIN cung dinh `transformers==4.46.3` cho ca hai
  nhanh model (xem giai thich chi tiet o muc 0). Neu ban cap nhat package nao khac ma vo tinh
  keo theo nang cap `transformers`, hay kiem tra lai bang `import transformers; transformers.__version__`
  truoc khi chay lai cac cell RAM++.
- **Dac diem cua label tu Grounding DINO (API cu)**: vi ban `transformers==4.46.3` chua co tham
  so tien loi `text_labels`, label tra ve duoc giai ma nguoc tu `input_ids` theo vung token co
  diem text-threshold cao, nen doi khi la mot phan cua tag (vi du "kitchen count" thay vi day du
  "kitchen counter top") hoac ghep 2 tag lien ke. Day la dac diem da biet cua co che decode nay,
  khong anh huong nhieu den muc dich minh hoa pipeline, nhung neu can label sach hon cho production,
  nen nang cap len mot phien ban `transformers` moi hon CHI cho nhanh Grounding DINO (chay trong
  mot moi truong/venv rieng, tach voi nhanh RAM++) de dung duoc tham so `text_labels`.
- **Toc do o quy mo lon**: paper xu ly ~300h video / ~32.5M khung hinh. O quy mo nay nen:
  - Chay `dino_model` va `ram_model` theo **batch** (gop nhieu anh trong 1 forward pass) thay vi
    tung anh nhu demo tren.
  - Dung `grounding-dino-base` (chinh xac hon) chi cho cac khung hinh duoc danh dau "kho"
    (vi du tag confidence thap), con lai dung `grounding-dino-tiny` de tiet kiem compute.
  - Export sang ONNX / TensorRT neu can inference real-time (paper dat muc tieu "enhancing
    real-time search capabilities" o phan Conclusion).
- **Nguong `box_threshold` / `text_threshold`**: nen tinh chinh theo tung domain (tin tuc, the
  thao, talkshow...) vi paper cung de cap toi viec tuy bien theo loai truy van.
- **Lien ket voi OCR & Caption**: theo Fig. 2, `objects` (Grounding DINO) va `tags` (RAM) la 2
  trong so 5 field duoc Elasticsearch index cung voi OCR (PaddleOCR), Caption (FuseCap) va
  Feature vector (CLIP/BLIP-2) -- tat ca duoc ket hop lai bang **Reciprocal Rank Fusion (RRF)**
  o buoc retrieval (cong thuc (2), muc 5.2 cua paper) de tranh cross-referencing giua cac nhanh.
- **Ket hop GPT (tuy chon)**: co the tai su dung doan code GPT o notebook goc (`RAM__.ipynb`,
  cell cuoi) de sinh caption tieng Viet tu `tags`, roi luu them vao `frame_metadata` nhu mot
  field `caption_vi`, hoan thien day du nhanh Backend trong Fig. 2.

"""